"""Homework 7: A collection of functions related to game-like operations and linguistic analysis."""

from langdetect import detect
import random


def generate_number():
    """Generate a random 4-digit number with non-repeating digits."""
    digits = list(range(10))
    random.shuffle(digits)
    if digits[0] == 0:
        digits[0], digits[1] = digits[1], digits[0]
    return digits[:4]


def check_guess(number, guess):
    """
    Check the guess against the generated number and return the count of bulls and cows.

    Args:
    number (list): The generated number as a list of digits.
    guess (list): The user's guess as a list of digits.

    Returns: tuple: A tuple containing the count of bulls (correct digit and position) and cows (correct digit but
    wrong position).
    """
    bulls = 0
    cows = 0
    for i in range(4):
        if guess[i] == number[i]:
            bulls += 1
        elif guess[i] in number:
            cows += 1
    return bulls, cows


def play_game():
    """Run the Bulls and Cows game where the user guesses a generated 4-digit number."""
    print("Bulls and Cows Game\n"
          "Game Rules:\n"
          "Your task is to guess a 4-digit number generated by the computer.\n"
          "After each attempt, the computer will inform you how many digits were guessed without matching their "
          "positions in"
          "the generated number (cows) and how many were guessed up to the positions in the generated number (bulls).")

    number = generate_number()
    attempts = 0

    while True:
        guess = input('Enter a 4-digit number with non-repeating digits: ')

        if len(guess) != 4 or not guess.isdigit():
            print('Please enter a 4-digit number.')
            continue

        guess = list(map(int, guess))

        if len(set(guess)) != 4:
            print('Please enter a number with non-repeating digits.')
            continue

        attempts += 1

        bulls, cows = check_guess(number, guess)
        print('Bulls: ', bulls)
        print('Cows: ', cows)

        if bulls == 4:
            print('You win!')
            break

        print()

    print('Generated number: ', ''.join(map(str, number)))
    print('Number of attempts: ', attempts)


play_game()


# Задание 2 'Like':

def like_count(names):
    """
    Count the likes for a social media post and format the display based on the language of the first name.

    Args:
    names (list): A list of names as strings.

    Returns:
    str: A formatted string representing the number of likes and names.
    """
    num_likes = len(names)
    lang = detect(names[0])
    if lang == 'ru':
        if num_likes == 1:
            return f'{names[0]} нравится это'
        elif num_likes == 2:
            return f'{names[0]} и {names[1]} нравится это'
        elif num_likes == 3:
            return f'{names[0]}, {names[1]} и {names[2]} нравится это'
        elif num_likes > 3:
            return f'{names[0]}, {names[1]} и еще {num_likes - 2} человек нравится это'
        else:
            return 'Никому это не нравится'
    elif lang == 'en':
        if num_likes == 1:
            return f'{names[0]} likes this'
        elif num_likes == 2:
            return f'{names[0]} and {names[1]} like this'
        elif num_likes == 3:
            return f'{names[0]}, {names[1]}, and {names[2]} like this'
        elif num_likes > 3:
            return f'{names[0]}, {names[1]}, and {num_likes - 2} others like this'
        else:
            return 'No one likes this'


names = input('Введите имена через запятую: ').split(',')

print(like_count(names))

# Задание 3 'BuzzFuzz':

lower = 0
upper = 0

while lower <= 0:
    lower = int(input('Введите начало интервала (должен быть положительным числом): '))
    if lower <= 0:
        print('Начало интервала должно быть положительным числом, повторите ввод.')

while upper <= lower:
    upper = int(input('Введите конец интервала (должен быть больше начала интервала): '))
    if upper <= lower:
        print('Конец интервала должен быть больше начала интервала, повторите ввод.')

for i in range(lower, upper + 1):
    if i % 3 == 0 and i % 5 == 0:
        print('FuzzBuzz')
    elif i % 3 == 0:
        print('Fuzz')
    elif i % 5 == 0:
        print('Buzz')
    else:
        print(i)
